{{- if .Values.flyteadmin.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "flyteadmin.name" . }}-grpc
  namespace: {{ template "flyte.namespace" . }}
  labels: {{ include "flyteadmin.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.flyteadmin.service.annotations }}
    {{ tpl ( .Values.flyteadmin.service.annotations | toYaml ) . | nindent 4 }}
    {{- end }}
    {{- if .Values.flyteadmin.service.grpcAnnotations }}
    {{ tpl ( .Values.flyteadmin.service.grpcAnnotations | toYaml ) . | nindent 4 }}
    {{- end }}
spec:
  {{- with .Values.flyteadmin.service.type}}
  type: {{ . }}
  {{- end }}
  {{- with .Values.flyteadmin.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{ . }}
  {{- end }}
  ports:
    - name: grpc
      port: 81
      protocol: TCP
      targetPort: 8089
  selector: {{ include "flyteadmin.selectorLabels" . | nindent 4 }}
{{- end }}
